identifier: l4ubmba2w3d8w913
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: biz-landing
homeFolder: /Users/ivankarbashevskyi/Projects/Organizations/beeoclock/biz-landing
distFolder: ./firebase/production/dist/biz-landing
outDir: >-
  /Users/ivankarbashevskyi/Projects/Organizations/beeoclock/biz-landing/firebase/production/dist/static
handle404: ''
allowErrorCollect: false
